### ISSUE TITLE
Initial setup issue

### ISSUE THREAD

**Issue by daveoconnor** [mikeando/gdocbak#7]
Hi, I'm trying to run gdocbak for the first time and using `RUST_BACKTRACE=full  gdocbak --store=data/google_docs --client-settings=/etc/gdocbak/service_account_key.json --credentials=tokencache.json` I get the backtrace below.

1. /etc/gdocbak/service_account_key.json contains what should be a valid key.
1. tokencache.json is an empty file, because the documentation says to run it that way and then a token will be presented after authentication. I get the same error without adding --credential or an empty value.

Should the initial run have some other value or set of arguments?

Thanks in advance.

```
thread 'main' panicked at src/main.rs:195:47:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fdbf6d66246 - std::backtrace_rs::backtrace::libunwind::trace::h7d9d6777fb8bb20d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fdbf6d66246 - std::backtrace_rs::backtrace::trace_unsynchronized::h9c973399eff3243c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdbf6d66246 - std::sys_common::backtrace::_print_fmt::hcfcb0438b59f41ac
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fdbf6d66246 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h12ff509796e7db1f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fdbf6da8430 - core::fmt::rt::Argument::fmt::h0f89a5eb60e0da5a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7fdbf6da8430 - core::fmt::write::hd2897b7ab92710d9
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fdbf6d632ff - std::io::Write::write_fmt::h7aec362f631668c1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7fdbf6d66024 - std::sys_common::backtrace::_print::h02de5e3a7ec93331
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fdbf6d66024 - std::sys_common::backtrace::print::h39dfbda16576800a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fdbf6d676f7 - std::panicking::default_hook::{{closure}}::h9d3976e3cec30e20
  10:     0x7fdbf6d67459 - std::panicking::default_hook::h8f0238c5452f23e8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7fdbf6d67b88 - std::panicking::rust_panic_with_hook::hc412fca92650d4b2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x7fdbf6d67a29 - std::panicking::begin_panic_handler::{{closure}}::hf6e9952ead3e2c54
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:     0x7fdbf6d66746 - std::sys_common::backtrace::__rust_end_short_backtrace::h1410a9c85ac94b3e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7fdbf6d677c0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x7fdbf6872ad5 - core::panicking::panic_fmt::h2838d0515af9b2ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x7fdbf6872b93 - core::panicking::panic::h584a128616e7fa9b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  17:     0x7fdbf6935f4f - gdocbak::main::{{closure}}::hf3e9a5ac1b03a15b
  18:     0x7fdbf6932149 - tokio::runtime::park::CachedParkThread::block_on::hb81523777af8fd57
  19:     0x7fdbf6964d2a - tokio::runtime::context::runtime::enter_runtime::h8b0aa0bee1124fbf
  20:     0x7fdbf68d64ee - tokio::runtime::runtime::Runtime::block_on::h917e52019d2b47f9
  21:     0x7fdbf6968589 - gdocbak::main::hb1e398fca3b6de66
  22:     0x7fdbf6909b83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4fac33ee64ab629c
  23:     0x7fdbf69bc509 - std::rt::lang_start::{{closure}}::hfead51ce907b5b90
  24:     0x7fdbf6d5d138 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbd70bf23aaabb1f2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  25:     0x7fdbf6d5d138 - std::panicking::try::do_call::h34a2aa1a42d8b296
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  26:     0x7fdbf6d5d138 - std::panicking::try::ha9060f095dce4b29
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  27:     0x7fdbf6d5d138 - std::panic::catch_unwind::h6bae8dd14d964496
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  28:     0x7fdbf6d5d138 - std::rt::lang_start_internal::{{closure}}::h4ced5aadb57c4e33
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  29:     0x7fdbf6d5d138 - std::panicking::try::do_call::hb890e897357f772c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  30:     0x7fdbf6d5d138 - std::panicking::try::h795efaa1580fa0bb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  31:     0x7fdbf6d5d138 - std::panic::catch_unwind::hcdb55523e22a6b5f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  32:     0x7fdbf6d5d138 - std::rt::lang_start_internal::h6c2766cc18ac837a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  33:     0x7fdbf6968655 - main
```

**Comment by daveoconnor** [comment]
This is what the redacted /etc/gdocbak/service_account_key.json passed in looks like:
```json
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "-----BEGIN PRIVATE KEY-----\n ... \n-----END PRIVATE KEY-----\n",
  "client_email": "",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/...",
  "universe_domain": "googleapis.com"
}

```

**Comment by mikeando** [comment]
I think that's not the format it is expecting. Looking at the code in the oauth crate, it seems it should be more like:

```
{
  "installed":{
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "client_email":"",
    ...
  }
}
```

i.e. you need to wrap everything inside an "installed" chunk.

The oauth code also suggests that this format is returned by the  [google developer console](https://code.google.com/apis/console).

```
/// A type to facilitate reading and writing the json secret file
/// as returned by the [google developer console](https://code.google.com/apis/console)
```

Let me know if that's enough to resolve your issue, and I'll update the docs to reflect it.

**Comment by daveoconnor** [comment]
Thanks for that, it pointed me in the right direction. I'd been trying to use service account credentials instead of credentials created specifically for oauth thinking they would just work. Seems not.

Hitting some other issues now around credentials that may benefit from documentation tweaks, so I'll add a PR when I can get back to this. 

Thanks for the help! Closing for now.

**Comment by daveoconnor** [comment]
I've gotten back to this now and I'm still facing issues. If I'm doing something wrong I'll provide a PR with updated docs based on your response but I think it's possibly a change in google's oath process now.

I changed my oauth credentials to new "desktop" ones, that's the only credential type that return json with an "installed" key.

Redacted version:

```js
{
  "installed": {
    "client_id": "....apps.googleusercontent.com",
    "project_id": "...",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "...",
    "redirect_uris": [
      "http://localhost"
    ]
  }
}
```

When I try to use them with `gdocbak --store=data/google_docs --client-settings=/etc/gdocbak/cliend_id.json` it provides me the following (redacted) link to use to retrieve a code: 
`https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive.metadata.readonly&access_type=offline&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=....apps.googleusercontent.com`

![oob](https://github.com/mikeando/gdocbak/assets/2774608/eba0b297-ea43-4083-ab6c-637267b07431)


The "developer documentation" linked from that image is: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

Is it possible that some changes need to be made for this new process, or am I doing something wrong still?
I started looking into trying to make the changes but lack of Rust knowledge blocked me.

Another idea: maybe support for service accounts would be the way to go? https://cloud.google.com/iam/docs/service-account-overview

Thanks in advance.

**Comment by mikeando** [comment]
Thats extremely annoying. IIRC It used to be that those APIs would work while your application was unpublished. I will need to go and check if my backup server has had failing requests for a while. (I don't use it for critical backups, and so don't have cron job monitoring etc set up)

Looking at the docs, it seems that all the other methods of authentication require you to either spin up an external service to auth against, or for service accounts, be part of a google workspace account.

I'm sorry, I don't have time to dig into implementing the external service route, and my accounts are not part of a google workspace, so I can't investigate the service account route either.

**Comment by daveoconnor** [comment]
I can understand the frustration.

I'll leave this open for now for anyone else who might want to use the project.

Thanks again for the quick response!
